#!/usr/bin/env bash
function barebones() {
    # 0. The project name
    project=$1

    # 1. Download latest version of WordPress into Sites folder
    cd ~/Sites
    wget https://wordpress.org/latest.tar.gz
    tar -xvzf latest.tar.gz

    # 2. Rename directory to given project name
    mv wordpress $project
    rm latest.tar.gz
    cd ~/Sites/$project

    # 3. Remove unnecessary files and create .gitignore file
    rm license.txt readme.html

    ## 3.1. Create .gitignore
    echo '.DS_Store
[Tt]humbs.db
.Trashes
.log
.env.php
sitemap.xml
wp-content/backup
wp-content/cache
wp-content/upgrade
wp-content/uploads
wp-content/blogs.dir
wp-content/backup-db
wp-content/advanced-cache.php
wp-content/wp-cache-config.php
wp-content/themes/*/.sass-cache
wp-content/themes/*/node_modules' > .gitignore

    ## 3.2. Remove unnecessary plugins
    cd wp-content/plugins
    rm -rf */ hello.php

    ## 3.3. Remove unnecessary themes
    cd ../themes
    rm -rf */

    # 4. Clone barebones
    git clone -b v2 https://github.com/benchmarkstudios/barebones
    mv barebones $project

    # 5. Install barebones submodules
    cd $project
    git submodule init
    git submodule update
    rm -rf .* assets/sass/vendor/simple-grid/.*

    # 6. Install all npm dependencies
    sudo npm install
}

barebones $1