#!/usr/bin/env bash
function barebones() {
    # 0. The project name
    project=$1

    # 1. Download latest version of WordPress into Sites folder
    cd ~/Sites
    wget https://wordpress.org/latest.tar.gz
    tar -xvzf latest.tar.gz

    # 2. Rename directory to given project name
    mv wordpress $project
    rm latest.tar.gz
    cd ~/Sites/$project

    # 3. Remove unnecessary files
    rm license.txt readme.html

    # 4. Create .gitignore file
    echo '.DS_Store
[Tt]humbs.db
.Trashes
.log
.env.php
sitemap.xml
wp-content/backup
wp-content/cache
wp-content/upgrade
wp-content/uploads
wp-content/blogs.dir
wp-content/backup-db
wp-content/advanced-cache.php
wp-content/wp-cache-config.php
wp-content/themes/*/.sass-cache
wp-content/themes/*/node_modules' > .gitignore

    # 5. Plugins
    ## 5.1. Remove unnecessary plugins
    cd wp-content/plugins
    rm -rf */ hello.php

    ## 5.2. Clone ACF PRO and Regenerate Thumbnails
    git clone https://github.com/wp-premium/advanced-custom-fields-pro.git
    git clone https://github.com/Viper007Bond/regenerate-thumbnails.git
    git clone https://github.com/Yoast/wordpress-seo.git

    # 6. Themes
    ## 6.1. Remove unnecessary themes
    cd ../themes
    rm -rf */

    ## 6.2. Clone barebones
    git clone -b v3 https://github.com/benchmarkstudios/barebones
    mv barebones $project

    ## 6.3. Install barebones submodules
    cd $project
    git submodule init
    git submodule update
    rm -rf .* README.md assets/sass/vendor/simple-grid/.* assets/sass/vendor/simple-grid/README.md

    # 7. Install all npm dependencies
    sudo npm install
}

barebones $1
