#!/usr/bin/env bash
function barebones() {

    # Variables
    GREEN='\033[0;32m'
    GREY='\033[0;90m'
    BOLD='\033[1;37m'
    RESET='\033[0m'

    # 0. The project name
    project=$1

    # 1. Download latest version of WordPress into Sites folder
    cd ~/Sites
    wget https://wordpress.org/latest.tar.gz
    tar -xvzf latest.tar.gz

    # 2. Rename directory to given project name
    mv wordpress $project
    rm latest.tar.gz
    cd ~/Sites/$project

    # 3. Remove unnecessary files
    rm license.txt readme.html

    # 4. Create .gitignore file
    echo '.DS_Store
[Tt]humbs.db
.Trashes
.log
.env.php
sitemap.xml
wp-content/backup
wp-content/cache
wp-content/upgrade
wp-content/uploads
wp-content/blogs.dir
wp-content/backup-db
wp-content/advanced-cache.php
wp-content/wp-cache-config.php
wp-content/themes/*/.sass-cache
wp-content/themes/*/node_modules' > .gitignore

    # 5. Plugins
    cd wp-content/plugins

    ## 5.1. Remove unnecessary plugins
    read -p "$(echo -e $GREEN"?"$RESET$BOLD" Do you want to remove unnecessary plugins?"$RESET$GREY" (y/n)"$RESET) " CONT INPUT_VARIABLE
    if [ "$CONT" = "y" ]; then
        rm -rf */ hello.php
    fi

    ## 5.2. Download useful plugins
    read -p "$(echo -e $GREEN"?"$RESET$BOLD" Do you want to install our recommended plugins?"$RESET$GREY" (y/n)"$RESET) " CONT INPUT_VARIABLE
    if [ "$CONT" = "y" ]; then
        git clone https://github.com/wp-premium/advanced-custom-fields-pro.git

        wget https://downloads.wordpress.org/plugin/regenerate-thumbnails.zip
        wget https://downloads.wordpress.org/plugin/simple-history.zip
        wget https://downloads.wordpress.org/plugin/wordpress-seo.zip
        wget https://downloads.wordpress.org/plugin/classic-editor.zip

        tar -xvzf regenerate-thumbnails.zip
        tar -xvzf simple-history.zip
        tar -xvzf wordpress-seo.zip
        tar -xvzf classic-editor.zip
        rm -rf *.zip */.git
    fi

    # 6. Themes
    ## 6.1. Remove unnecessary themes
    cd ../themes
    rm -rf */

    ## 6.2. Clone barebones
    echo -e "${GREEN}?${RESET} ${BOLD}Choose the Barebones version you want to install:${RESET}"

    PS3='Please select an option: '

    options=("3.0.0 LST" "3.1.0 Current")
    select opt in "${options[@]}"
    do
        case $opt in
            "3.1.0 Current")
                git clone -b v3.1.0 https://github.com/benchmarkstudios/barebones
                break
                ;;
            "3.0.0 LST")
                git clone https://github.com/benchmarkstudios/barebones
                break
                ;;
            *) 
                echo "Invalid option $REPLY"
                ;;
        esac
    done
    
    mv barebones $project

    ## 6.3. Install barebones submodules
    cd $project
    git submodule init
    git submodule update

    ## 6.4. Remove unnecessary stuff
    rm -rf .git .gitattributes .gitignore .gitmodules README.md CHANGELOG.md assets/styles/vendor/*/.* assets/styles/vendor/*/README.md
    
    ## 6.5 Create ACF folder
    mkdir acf-json

    # 7. Install all npm dependencies
    npm install

    # 8. Fix potential problems
    npm audit fix --force
}

barebones $1
